General:
  originals_folder: data-tests
  output_folder: output-tests
  airports_extended: airports-extended.csv
atmosfair:
  responses_folder: 'atmosfair_responses'
legs:
  spesen:
    - '[all-spesen-test-data.xlsx]Table1'
  airplus:
    - '[all-airplus-test-data.xlsx]Table1'
  bta:
    - '[all-bta-test-data]Table1'
HR:
  excerpts:
    2017:
      - '[2017-hr-test-data.xlsx]Sheet1'
    2018:
      - '[2018-hr-test-data.xlsx]Sheet1'
    2019:
      - '[2019-hr-test-data.xlsx]Sheet1'
    2020:
      - '[2020-hr-test-data.xlsx]Sheet1'
    top_departments: [A, G, L, N, P, R, S, T, V, W]
    matches_folder: hr_bta_matches
    outputs:
      proposed_matches_basename: hr_bta_matches