General:
  originals_folder: data-tests
  output_folder: output-tests
  airports_extended: airports-extended.csv
atmosfair:
  responses_folder: "atmosfair_responses"
legs:
  spesen:
    - "[spesen-legs-base.xlsx]Sheet1"
  airplus:
    - "[airplus-legs-base.xlsx]Sheet1"
  bta:
    - "[bta-legs-base.xlsx]Sheet1"
HR:
  excerpts:
    2017:
      - "[hr-before-2019-base.xlsx]Sheet1"
    2018:
      - "[hr-before-2019-base.xlsx]Sheet1"
    2019:
      - "[hr-since-2019-base.xlsx]Sheet1"
    2020:
      - "[hr-since-2019-base.xlsx]Sheet1"
  top_departments: [A, G, L, N, P, R, S, T, V, W]
  matches_folder: hr_bta_matches
  outputs:
    proposed_matches_basename: hr_bta_matches
